#配置端口号
server:
  port: 8001

#配置mybatis-plus
mybatis-plus:
  #配置别名
  type-aliases-package: com.feng.springCloud.pojo
  #  #mybatis-plus配置路径
  #  config-location: classpath:mybatis/mybatis-config.xml
  #mapper配置路径
  mapper-locations: classpath:mybatis/mapper/*.xml

#配置spring
spring:
  application:
    #给这个工程起个名字，一定要见字知义
    name: springCloud-provider-8001
  #配置数据源
  datasource:
    #配置数据源
    type: com.alibaba.druid.pool.DruidDataSource
    name: datasource
    #驱动
    driver-class-name: org.gjt.mm.mysql.Driver
    #数据库url，数据库名称根据自己的定
    url: jdbc:mysql://localhost:3307/shiwangeweishenme?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: Jason20040903
    #通过别名的方式配置扩展插件,stat日志用的filter
    filters: stat
    #最大连接池数量
    maxActive: 20
    #初始化时建立物理连接的个数
    initialSize: 5
    #获取连接时最大等待时间，单位毫秒
    maxWait: 60000
    #最小连接池数量，已经不再使用了
    minIdle: 1
    #每60秒运行一次空闲连接回收器
    timeBetweenEvictionRunsMillis: 60000
    #池中的连接空闲30分钟后被回收,默认值就是30分钟
    minEvictableIdleTimeMillis: 1800000
    #验证连接是否可用，使用的SQL语句
    validationQuery: select 1 from dual
    #指明连接是否被空闲连接回收器(如果有)进行检验.如果检测失败,则连接将被从池中去除
    testWhileIdle: true
    #借出连接时不要测试，否则很影响性能
    testOnBorrow: false
    #归还连接时执行validationQuery检测连接是否有效，做了这个配置会降低性能
    testOnReturn: false
    #是否缓存preparedStatement，也就是PSCache;PSCache对支持游标的数据库性能提升巨大，比如说oracle。在mysql下建议关闭
    poolPreparedStatements: true
    #要启用PSCache，必须配置大于0，当大于0时，poolPreparedStatements自动触发修改为true
    maxOpenPreparedStatements: -1

# 配置Eureka, 把服务注册到哪里，哪个eu
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8002/eureka/