spring:
  application:
    name: spring-cloud-provider-8007  #微服务名称，对外暴漏的微服务名称，十分重要

  data:
    mongodb:
      authentication-database: admin
      host: localhost
      port: 27017
      database: myblog


server:
  port: 8007
########################################### Spring cloud 自定义服务名称和 ip 地址###############################################
eureka:
  client: #将客户端注册到 eureka 服务列表内
    service-url:
      #defaultZone: http://eureka7001:7001/eureka  #这个地址是 7001注册中心在 application.yml 中暴露出来额注册地址 （单机版）
      defaultZone: http://eureka8002:8002/eureka/, http://eureka8003:8003/eureka/  #将服务注册到 Eureka 集群
  instance:
    instance-id: spring-cloud-provider-8007 #自定义服务名称信息
    prefer-ip-address: true  #显示访问路径的 ip 地址
#####################spring cloud 使用 Spring Boot actuator 监控完善信息###########################################
# Spring Boot 2.50对 actuator 监控屏蔽了大多数的节点，只暴露了 heath 节点，本段配置（*）就是为了开启所有的节点
management:
  endpoints:
    web:
      exposure:
        include: "*"   # * 在yaml 文件属于关键字，所以需要加引号

info:
  app:
    name: node16-boot-actuator
    port: 8007
    version: 1.0.0
    author: cicada

minio:
  config:
    url: http://localhost:9000/
    accessKey: gAjYSAJDImJP9ZvqgJB6
    secretKey: cb8SkANxDCm90kdLz2puij4U7J8ZmlTBWAHYInT3
    secure: false
    bucketName: myblogbucket

# 这要开，不然feign会找不到这个provider
security:
  open: Y